### ISSUE TITLE
Can't connect to mac server (IPSec NAT traversal issue?)

### ISSUE THREAD

**Issue by pawelwnuq** [seriyps/NetworkManager-l2tp#12]
Hi,
I'm trying to connect to mac server vpn using Network Manager.
I'm using Fedora19 (3.12.5-200.fc19.x86_64)
I add connection, next I provide my pre-shered password in IPsec settings. I leave gateway Id empty.

[root@localhost ipsec.d]# /usr/libexec/nm-l2tp-service --debug
** Message: nm-l2tp-service (version 0.9.8.0) starting...
connection
	name : "connection"
	id : "VPN 1" (s)
	uuid : "7852d45a-5564-41dc-a317-2c585676279d" (s)
	type : "vpn" (s)
	permissions : ['user:wnk:'] (s)
	autoconnect : FALSE (s)
	timestamp : 0 (sd)
	read-only : FALSE (sd)
	zone : NULL (sd)
	master : NULL (sd)
	slave-type : NULL (sd)
	secondaries : [] (sd)

vpn
	name : "vpn"
	service-type : "org.freedesktop.NetworkManager.l2tp" (s)
	user-name : "wnk" (s)
	data : [ { 'lcp-echo-interval': 30 }, { 'password-flags': 1 }, { 'ipsec-group-name': newton }, { 'ipsec-psk': password }, { 'user': me }, { 'ipsec-enabled': yes }, { 'lcp-echo-failure': 5 }, { 'gateway': ******* }, { 'domain': ******* }, ] (s)
	secrets : [ { 'password': ****** }, ] (s)

ipv6
	name : "ipv6"
	method : "auto" (s)
	dhcp-hostname : NULL (sd)
	dns : [] (s)
	dns-search : [] (sd)
	addresses : [] (s)
	routes : [] (s)
	ignore-auto-routes : FALSE (sd)
	ignore-auto-dns : FALSE (sd)
	never-default : FALSE (sd)
	may-fail : TRUE (sd)
	ip6-privacy : -1 (sd)

ipv4
	name : "ipv4"
	method : "auto" (s)
	dns : [] (s)
	dns-search : [] (sd)
	addresses : [] (s)
	routes : [] (s)
	ignore-auto-routes : FALSE (sd)
	ignore-auto-dns : FALSE (sd)
	dhcp-client-id : NULL (sd)
	dhcp-send-hostname : TRUE (sd)
	dhcp-hostname : NULL (sd)
	never-default : TRUE (s)
	may-fail : TRUE (sd)

** Message: Use '********' as a gateway
** Message: Check port 1701
** Message: ipsec enable flag: yes
** Message: starting ipsec
Redirecting to: systemctl stop+start ipsec.service
whack: Pluto is not running (no "/var/run/pluto/pluto.ctl")
002 forgetting secrets
002 loading secrets from "/etc/ipsec.secrets"
Warning: ignored obsolete keyword 'force_keepalive'
opening file: /var/run/nm-ipsec-l2tp.3719/ipsec.conf
debugging mode enabled
end of file /var/run/nm-ipsec-l2tp.3719/ipsec.conf
Warning: ignored obsolete keyword 'force_keepalive'
Loading conn nm-ipsec-l2tpd-3719
connection's  policy label: (null)
starter: case KH_DEFAULTROUTE: empty
loading named conns: nm-ipsec-l2tpd-3719
parse_src = 1, parse_gateway = 0, has_dst = 1
dst '********' via 192.168.1.1 dev wlp12s0 src 192.168.1.102
set addr: 192.168.1.102
conn: "nm-ipsec-l2tpd-3719" loopback=0
conn: "nm-ipsec-l2tpd-3719" labeled_ipsec=0
conn: "nm-ipsec-l2tpd-3719" policy_label=0
002 "nm-ipsec-l2tpd-3719": deleting connection
002 added connection description "nm-ipsec-l2tpd-3719"
002 "nm-ipsec-l2tpd-3719" #1: initiating Main Mode
104 "nm-ipsec-l2tpd-3719" #1: STATE_MAIN_I1: initiate
003 "nm-ipsec-l2tpd-3719" #1: received Vendor ID payload [RFC 3947]
003 "nm-ipsec-l2tpd-3719" #1: received Vendor ID payload [Dead Peer Detection]
002 "nm-ipsec-l2tpd-3719" #1: enabling possible NAT-traversal with method RFC 3947 (NAT-Traversal)
002 "nm-ipsec-l2tpd-3719" #1: transition from state STATE_MAIN_I1 to state STATE_MAIN_I2
106 "nm-ipsec-l2tpd-3719" #1: STATE_MAIN_I2: sent MI2, expecting MR2
002 "nm-ipsec-l2tpd-3719" #1: I will NOT send an initial contact payload
003 "nm-ipsec-l2tpd-3719" #1: NAT-Traversal: Result using RFC 3947 (NAT-Traversal): both are NATed
002 "nm-ipsec-l2tpd-3719" #1: Not sending INITIAL_CONTACT
002 "nm-ipsec-l2tpd-3719" #1: transition from state STATE_MAIN_I2 to state STATE_MAIN_I3
108 "nm-ipsec-l2tpd-3719" #1: STATE_MAIN_I3: sent MI3, expecting MR3
002 "nm-ipsec-l2tpd-3719" #1: Main mode peer ID is ID_IPV4_ADDR: '10.0.1.2'
003 "nm-ipsec-l2tpd-3719" #1: we require peer to have ID '(server ip here)', but peer declares '10.0.1.2'
218 "nm-ipsec-l2tpd-3719" #1: STATE_MAIN_I3: INVALID_ID_INFORMATION
002 "nm-ipsec-l2tpd-3719" #1: sending encrypted notification INVALID_ID_INFORMATION to ********:4500

I had similar issue on windows, but I could handle it following this steps http://support.apple.com/kb/ht5078. 

Is this a bug, or there is something wrong with my configuration?

ps. there is no field gateway Id on windows and OSx. I tried to set there '10.0.1.2' but then I had 
003 "nm-ipsec-l2tpd-3719" #1: we require peer to have ID '@10.0.1.2', but peer declares '10.0.1.2'
in logs, and same result.

**Comment by seriyps** [comment]
Project development was moved to https://github.com/nm-l2tp/network-manager-l2tp
If you feel that this problem wasn't resolved, please, re-create this issue on this new project.
