### ISSUE TITLE
IPSEC options

### ISSUE THREAD

**Issue by Robert0812** [seriyps/NetworkManager-l2tp#14]
Hi, Sergey, 

Thanks for the great tool, but I have some problems in configuring the L2TP VPN with it.  
In IPSEC options, group name and gateway ID are required to fill, but I don't know what they are. How do set pre-shared key without setting group name and gateway ID?

**Comment by seriyps** [comment]
Project development was moved to https://github.com/nm-l2tp/network-manager-l2tp
If you feel that this problem wasn't resolved, please, re-create this issue on this new project.
