### ISSUE TITLE
Can not build in Arch Linux

### ISSUE THREAD

**Issue by acgtyrant** [seriyps/NetworkManager-l2tp#16]
Nice plugin! 

But I can not build it successfully it in my Arch Linux...

Here the error is:

    libtoolize: putting auxiliary files in `.'.
    libtoolize: linking file `./ltmain.sh'
    libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
    libtoolize: linking file `m4/libtool.m4'
    libtoolize: linking file `m4/ltoptions.m4'
    libtoolize: linking file `m4/ltsugar.m4'
    libtoolize: linking file `m4/ltversion.m4'
    libtoolize: linking file `m4/lt~obsolete.m4'
    configure.ac:14: installing './compile'
    configure.ac:17: installing './config.guess'
    configure.ac:17: installing './config.sub'
    configure.ac:4: installing './install-sh'
    configure.ac:4: installing './missing'
    auth-dialog/Makefile.am:1: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
    auth-dialog/Makefile.am: installing './depcomp'
    src/Makefile.am:1: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
    auth-dialog/Makefile.am:1: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
    src/Makefile.am:1: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
    checking for gawk... gawk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... yes
    checking whether to enable maintainer-specific portions of Makefiles... yes
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking for style of include used by make... GNU
    checking dependency style of gcc... gcc3
    checking build system type... x86_64-unknown-linux-gnu
    checking host system type... x86_64-unknown-linux-gnu
    checking how to print strings... printf
    checking for a sed that does not truncate output... /usr/bin/sed
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for egrep... /usr/bin/grep -E
    checking for fgrep... /usr/bin/grep -F
    checking for ld used by gcc... /usr/bin/ld
    checking if the linker (/usr/bin/ld) is GNU ld... yes
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 1572864
    checking whether the shell understands some XSI constructs... yes
    checking whether the shell understands "+="... yes
    checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
    checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
    checking for /usr/bin/ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for dlltool... no
    checking how to associate runtime and link libraries... printf %s\n
    checking for ar... ar
    checking for archiver @FILE support... @
    checking for strip... strip
    checking for ranlib... ranlib
    checking command to parse /usr/bin/nm -B output from gcc object... ok
    checking for sysroot... no
    checking for mt... no
    checking if : is a manifest tool... no
    checking how to run the C preprocessor... gcc -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... no
    checking for gcc option to produce PIC... -fPIC -DPIC
    checking if gcc PIC flag -fPIC -DPIC works... yes
    checking if gcc static flag -static works... yes
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
    checking whether -lc should be explicitly linked in... no
    checking dynamic linker characteristics... GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... yes
    checking for ANSI C header files... (cached) yes
    checking fcntl.h usability... yes
    checking fcntl.h presence... yes
    checking for fcntl.h... yes
    checking paths.h usability... yes
    checking paths.h presence... yes
    checking for paths.h... yes
    checking sys/ioctl.h usability... yes
    checking sys/ioctl.h presence... yes
    checking for sys/ioctl.h... yes
    checking sys/time.h usability... yes
    checking sys/time.h presence... yes
    checking for sys/time.h... yes
    checking syslog.h usability... yes
    checking syslog.h presence... yes
    checking for syslog.h... yes
    checking for unistd.h... (cached) yes
    checking pppd/pppd.h usability... yes
    checking pppd/pppd.h presence... yes
    checking for pppd/pppd.h... yes
    checking for mode_t... yes
    checking for pid_t... yes
    checking whether time.h and sys/time.h may both be included... yes
    checking whether gcc needs -traditional... no
    checking for working memcmp... yes
    checking for select... yes
    checking for socket... yes
    checking for uname... yes
    checking whether NLS is requested... yes
    checking for intltool >= 0.35... 0.50.2 found
    checking for intltool-update... /usr/bin/intltool-update
    checking for intltool-merge... /usr/bin/intltool-merge
    checking for intltool-extract... /usr/bin/intltool-extract
    checking for xgettext... /usr/bin/xgettext
    checking for msgmerge... /usr/bin/msgmerge
    checking for msgfmt... /usr/bin/msgfmt
    checking for gmsgfmt... /usr/bin/msgfmt
    checking for perl... /usr/bin/perl
    checking for perl >= 5.8.1... 5.20.0
    checking for XML::Parser... ok
    checking locale.h usability... yes
    checking locale.h presence... yes
    checking for locale.h... yes
    checking for LC_MESSAGES... yes
    checking libintl.h usability... yes
    checking libintl.h presence... yes
    checking for libintl.h... yes
    checking for ngettext in libc... yes
    checking for dgettext in libc... yes
    checking for bind_textdomain_codeset... yes
    checking for msgfmt... (cached) /usr/bin/msgfmt
    checking for dcgettext... yes
    checking if msgfmt accepts -c... yes
    checking for gmsgfmt... (cached) /usr/bin/msgfmt
    checking for xgettext... (cached) /usr/bin/xgettext
    checking for pkg-config... /usr/bin/pkg-config
    checking pkg-config is at least version 0.9.0... yes
    checking for GTHREAD... yes
    checking for DBUS... yes
    checking for NM... yes
    checking for GTK... yes
    checking for GNOMEKEYRING... yes
    checking for more warnings... yes
    checking whether gcc understands -Wshadow... yes
    checking whether gcc understands -Wmissing-declarations... yes
    checking whether gcc understands -Wmissing-prototypes... yes
    checking whether gcc understands -Wdeclaration-after-statement... yes
    checking whether gcc understands -Wstrict-prototypes... yes
    checking whether gcc understands -Wfloat-equal... yes
    checking whether gcc understands -Wno-unused-parameter... yes
    checking whether gcc understands -Wno-sign-compare... yes
    checking whether gcc understands -fno-strict-aliasing... yes
    checking whether gcc understands -Wno-unused-but-set-variable... yes
    checking that generated files are newer than configure... done
    configure: creating ./config.status
    config.status: creating Makefile
    config.status: creating src/Makefile
    config.status: creating auth-dialog/Makefile
    config.status: creating properties/Makefile
    config.status: creating po/Makefile.in
    config.status: creating config.h
    config.status: executing depfiles commands
    config.status: executing libtool commands
    config.status: executing default-1 commands
    config.status: executing po/stamp-it commands
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
    checking for gawk... gawk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... yes
    checking whether to enable maintainer-specific portions of Makefiles... no
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking for style of include used by make... GNU
    checking dependency style of gcc... gcc3
    checking build system type... x86_64-unknown-linux-gnu
    checking host system type... x86_64-unknown-linux-gnu
    checking how to print strings... printf
    checking for a sed that does not truncate output... /usr/bin/sed
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for egrep... /usr/bin/grep -E
    checking for fgrep... /usr/bin/grep -F
    checking for ld used by gcc... /usr/bin/ld
    checking if the linker (/usr/bin/ld) is GNU ld... yes
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 1572864
    checking whether the shell understands some XSI constructs... yes
    checking whether the shell understands "+="... yes
    checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
    checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
    checking for /usr/bin/ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for dlltool... no
    checking how to associate runtime and link libraries... printf %s\n
    checking for ar... ar
    checking for archiver @FILE support... @
    checking for strip... strip
    checking for ranlib... ranlib
    checking command to parse /usr/bin/nm -B output from gcc object... ok
    checking for sysroot... no
    checking for mt... no
    checking if : is a manifest tool... no
    checking how to run the C preprocessor... gcc -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... no
    checking for gcc option to produce PIC... -fPIC -DPIC
    checking if gcc PIC flag -fPIC -DPIC works... yes
    checking if gcc static flag -static works... yes
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
    checking whether -lc should be explicitly linked in... no
    checking dynamic linker characteristics... GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... yes
    checking for ANSI C header files... (cached) yes
    checking fcntl.h usability... yes
    checking fcntl.h presence... yes
    checking for fcntl.h... yes
    checking paths.h usability... yes
    checking paths.h presence... yes
    checking for paths.h... yes
    checking sys/ioctl.h usability... yes
    checking sys/ioctl.h presence... yes
    checking for sys/ioctl.h... yes
    checking sys/time.h usability... yes
    checking sys/time.h presence... yes
    checking for sys/time.h... yes
    checking syslog.h usability... yes
    checking syslog.h presence... yes
    checking for syslog.h... yes
    checking for unistd.h... (cached) yes
    checking pppd/pppd.h usability... yes
    checking pppd/pppd.h presence... yes
    checking for pppd/pppd.h... yes
    checking for mode_t... yes
    checking for pid_t... yes
    checking whether time.h and sys/time.h may both be included... yes
    checking whether gcc needs -traditional... no
    checking for working memcmp... yes
    checking for select... yes
    checking for socket... yes
    checking for uname... yes
    checking whether NLS is requested... yes
    checking for intltool >= 0.35... 0.50.2 found
    checking for intltool-update... /usr/bin/intltool-update
    checking for intltool-merge... /usr/bin/intltool-merge
    checking for intltool-extract... /usr/bin/intltool-extract
    checking for xgettext... /usr/bin/xgettext
    checking for msgmerge... /usr/bin/msgmerge
    checking for msgfmt... /usr/bin/msgfmt
    checking for gmsgfmt... /usr/bin/msgfmt
    checking for perl... /usr/bin/perl
    checking for perl >= 5.8.1... 5.20.0
    checking for XML::Parser... ok
    checking locale.h usability... yes
    checking locale.h presence... yes
    checking for locale.h... yes
    checking for LC_MESSAGES... yes
    checking libintl.h usability... yes
    checking libintl.h presence... yes
    checking for libintl.h... yes
    checking for ngettext in libc... yes
    checking for dgettext in libc... yes
    checking for bind_textdomain_codeset... yes
    checking for msgfmt... (cached) /usr/bin/msgfmt
    checking for dcgettext... yes
    checking if msgfmt accepts -c... yes
    checking for gmsgfmt... (cached) /usr/bin/msgfmt
    checking for xgettext... (cached) /usr/bin/xgettext
    checking for pkg-config... /usr/bin/pkg-config
    checking pkg-config is at least version 0.9.0... yes
    checking for GTHREAD... yes
    checking for DBUS... yes
    checking for NM... yes
    checking for GTK... yes
    checking for GNOMEKEYRING... yes
    checking for more warnings... yes
    checking whether gcc understands -Wshadow... yes
    checking whether gcc understands -Wmissing-declarations... yes
    checking whether gcc understands -Wmissing-prototypes... yes
    checking whether gcc understands -Wdeclaration-after-statement... yes
    checking whether gcc understands -Wstrict-prototypes... yes
    checking whether gcc understands -Wfloat-equal... yes
    checking whether gcc understands -Wno-unused-parameter... yes
    checking whether gcc understands -Wno-sign-compare... yes
    checking whether gcc understands -fno-strict-aliasing... yes
    checking whether gcc understands -Wno-unused-but-set-variable... yes
    checking that generated files are newer than configure... done
    configure: creating ./config.status
    config.status: creating Makefile
    config.status: creating src/Makefile
    config.status: creating auth-dialog/Makefile
    config.status: creating properties/Makefile
    config.status: creating po/Makefile.in
    config.status: creating config.h
    config.status: config.h is unchanged
    config.status: executing depfiles commands
    config.status: executing libtool commands
    config.status: executing default-1 commands
    config.status: executing po/stamp-it commands
    make  all-recursive
    make[1]: Entering directory '/tmp/yaourt-tmp-acgtyrant/aur-networkmanager-l2tp/src/NetworkManager-l2tp-0.9.8'
    Making all in src
    make[2]: Entering directory '/tmp/yaourt-tmp-acgtyrant/aur-networkmanager-l2tp/src/NetworkManager-l2tp-0.9.8/src'
    dbus-binding-tool --prefix=nm_l2tp_pppd_service --mode=glib-server --output=nm-l2tp-pppd-service-glue.h ../src/nm-l2tp-pppd-service.xml
    make  all-am
    make[3]: Entering directory '/tmp/yaourt-tmp-acgtyrant/aur-networkmanager-l2tp/src/NetworkManager-l2tp-0.9.8/src'
    /bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I.. -I..   -I/usr/include/NetworkManager -I/usr/include/libnm-glib -I/usr/include/NetworkManager -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -D_FORTIFY_SOURCE=2  -Wall -std=gnu89 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -Wshadow -Wmissing-declarations -Wmissing-prototypes -Wdeclaration-after-statement -Wstrict-prototypes -Wfloat-equal -Wno-unused-parameter -Wno-sign-compare -fno-strict-aliasing -Wno-unused-but-set-variable -Werror -MT nm_l2tp_pppd_plugin_la-nm-l2tp-pppd-plugin.lo -MD -MP -MF .deps/nm_l2tp_pppd_plugin_la-nm-l2tp-pppd-plugin.Tpo -c -o nm_l2tp_pppd_plugin_la-nm-l2tp-pppd-plugin.lo `test -f 'nm-l2tp-pppd-plugin.c' || echo './'`nm-l2tp-pppd-plugin.c
    libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I.. -I/usr/include/NetworkManager -I/usr/include/libnm-glib -I/usr/include/NetworkManager -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_FORTIFY_SOURCE=2 -Wall -std=gnu89 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -Wshadow -Wmissing-declarations -Wmissing-prototypes -Wdeclaration-after-statement -Wstrict-prototypes -Wfloat-equal -Wno-unused-parameter -Wno-sign-compare -fno-strict-aliasing -Wno-unused-but-set-variable -Werror -MT nm_l2tp_pppd_plugin_la-nm-l2tp-pppd-plugin.lo -MD -MP -MF .deps/nm_l2tp_pppd_plugin_la-nm-l2tp-pppd-plugin.Tpo -c nm-l2tp-pppd-plugin.c  -fPIC -DPIC -o .libs/nm_l2tp_pppd_plugin_la-nm-l2tp-pppd-plugin.o
    libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I.. -I/usr/include/NetworkManager -I/usr/include/libnm-glib -I/usr/include/NetworkManager -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_FORTIFY_SOURCE=2 -Wall -std=gnu89 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -Wshadow -Wmissing-declarations -Wmissing-prototypes -Wdeclaration-after-statement -Wstrict-prototypes -Wfloat-equal -Wno-unused-parameter -Wno-sign-compare -fno-strict-aliasing -Wno-unused-but-set-variable -Werror -MT nm_l2tp_pppd_plugin_la-nm-l2tp-pppd-plugin.lo -MD -MP -MF .deps/nm_l2tp_pppd_plugin_la-nm-l2tp-pppd-plugin.Tpo -c nm-l2tp-pppd-plugin.c -o nm_l2tp_pppd_plugin_la-nm-l2tp-pppd-plugin.o >/dev/null 2>&1
    mv -f .deps/nm_l2tp_pppd_plugin_la-nm-l2tp-pppd-plugin.Tpo .deps/nm_l2tp_pppd_plugin_la-nm-l2tp-pppd-plugin.Plo
    /bin/sh ../libtool  --tag=CC   --mode=link gcc  -Wall -std=gnu89 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -Wshadow -Wmissing-declarations -Wmissing-prototypes -Wdeclaration-after-statement -Wstrict-prototypes -Wfloat-equal -Wno-unused-parameter -Wno-sign-compare -fno-strict-aliasing -Wno-unused-but-set-variable -Werror -module -avoid-version -Wl,-O1,--sort-common,--as-needed,-z,relro -o nm-l2tp-pppd-plugin.la -rpath /usr/lib/pppd/2.4.5 nm_l2tp_pppd_plugin_la-nm-l2tp-pppd-plugin.lo   -lnm-util -lnm-glib -lnm-glib-vpn -ldbus-glib-1 -ldbus-1 -lgobject-2.0 -lglib-2.0  
    libtool: link: gcc -shared  -fPIC -DPIC  .libs/nm_l2tp_pppd_plugin_la-nm-l2tp-pppd-plugin.o   -lnm-util -lnm-glib -lnm-glib-vpn -ldbus-glib-1 -ldbus-1 -lgobject-2.0 -lglib-2.0  -march=x86-64 -mtune=generic -O2 -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z -Wl,relro   -Wl,-soname -Wl,nm-l2tp-pppd-plugin.so -o .libs/nm-l2tp-pppd-plugin.so
    libtool: link: ar cru .libs/nm-l2tp-pppd-plugin.a  nm_l2tp_pppd_plugin_la-nm-l2tp-pppd-plugin.o
    libtool: link: ranlib .libs/nm-l2tp-pppd-plugin.a
    libtool: link: ( cd ".libs" && rm -f "nm-l2tp-pppd-plugin.la" && ln -s "../nm-l2tp-pppd-plugin.la" "nm-l2tp-pppd-plugin.la" )
    depbase=`echo nm-l2tp-service.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
    gcc -DHAVE_CONFIG_H -I. -I.. -I..  -pthread -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -I/usr/include/NetworkManager -I/usr/include/libnm-glib -I/usr/include/NetworkManager -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -DG_DISABLE_DEPRECATED -DBINDIR=\"/usr/bin\" -DPREFIX=\""/usr"\" -DSYSCONFDIR=\""/etc"\" -DNM_VERSION="\"0.9.8.0\"" -DLIBDIR=\""/usr/lib"\" -DLIBEXECDIR=\""/usr/lib/networkmanager"\" -DLOCALSTATEDIR=\""/usr/var"\" -DDATADIR=\"/usr/share\" -DNM_L2TP_LOCALEDIR=\"/usr/share/locale\" -DPLUGINDIR=\"/usr/lib/pppd/2.4.5\"  -D_FORTIFY_SOURCE=2  -Wall -std=gnu89 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -Wshadow -Wmissing-declarations -Wmissing-prototypes -Wdeclaration-after-statement -Wstrict-prototypes -Wfloat-equal -Wno-unused-parameter -Wno-sign-compare -fno-strict-aliasing -Wno-unused-but-set-variable -Werror -MT nm-l2tp-service.o -MD -MP -MF $depbase.Tpo -c -o nm-l2tp-service.o nm-l2tp-service.c &&\
    mv -f $depbase.Tpo $depbase.Po
    /bin/sh ../libtool  --tag=CC   --mode=link gcc  -Wall -std=gnu89 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -Wshadow -Wmissing-declarations -Wmissing-prototypes -Wdeclaration-after-statement -Wstrict-prototypes -Wfloat-equal -Wno-unused-parameter -Wno-sign-compare -fno-strict-aliasing -Wno-unused-but-set-variable -Werror  -Wl,-O1,--sort-common,--as-needed,-z,relro -o nm-l2tp-service nm-l2tp-service.o  -lgthread-2.0 -pthread -lglib-2.0  -lnm-util -lnm-glib -lnm-glib-vpn -ldbus-glib-1 -ldbus-1 -lgobject-2.0 -lglib-2.0  
    libtool: link: gcc -Wall -std=gnu89 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -Wshadow -Wmissing-declarations -Wmissing-prototypes -Wdeclaration-after-statement -Wstrict-prototypes -Wfloat-equal -Wno-unused-parameter -Wno-sign-compare -fno-strict-aliasing -Wno-unused-but-set-variable -Werror -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z -Wl,relro -o nm-l2tp-service nm-l2tp-service.o -pthread  -lgthread-2.0 -lnm-util -lnm-glib -lnm-glib-vpn -ldbus-glib-1 -ldbus-1 -lgobject-2.0 -lglib-2.0 -pthread
    make[3]: Leaving directory '/tmp/yaourt-tmp-acgtyrant/aur-networkmanager-l2tp/src/NetworkManager-l2tp-0.9.8/src'
    make[2]: Leaving directory '/tmp/yaourt-tmp-acgtyrant/aur-networkmanager-l2tp/src/NetworkManager-l2tp-0.9.8/src'
    Making all in auth-dialog
    make[2]: Entering directory '/tmp/yaourt-tmp-acgtyrant/aur-networkmanager-l2tp/src/NetworkManager-l2tp-0.9.8/auth-dialog'
    gcc -DHAVE_CONFIG_H -I. -I.. -I.. -I/usr/include/NetworkManager -I/usr/include/libnm-glib -I/usr/include/NetworkManager -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -pthread -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -DGDK_VERSION_MIN_REQUIRED=GDK_VERSION_3_0 -I/usr/include/gnome-keyring-1 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -DICONDIR=\""/usr/share/pixmaps"\" -DUIDIR=\"""\" -DBINDIR=\""/usr/bin"\" -DG_DISABLE_DEPRECATED -DVERSION=\"0.9.8.0\" -D_FORTIFY_SOURCE=2  -Wall -std=gnu89 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -Wshadow -Wmissing-declarations -Wmissing-prototypes -Wdeclaration-after-statement -Wstrict-prototypes -Wfloat-equal -Wno-unused-parameter -Wno-sign-compare -fno-strict-aliasing -Wno-unused-but-set-variable -Werror -MT nm_l2tp_auth_dialog-main.o -MD -MP -MF .deps/nm_l2tp_auth_dialog-main.Tpo -c -o nm_l2tp_auth_dialog-main.o `test -f 'main.c' || echo './'`main.c
    main.c: In function ‘keyring_lookup_secret’:
    main.c:56:2: error: ‘gnome_keyring_find_itemsv_sync’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring.h:325): Use 'secret_service_search_sync' instead [-Werror=deprecated-declarations]
      ret = gnome_keyring_find_itemsv_sync (GNOME_KEYRING_ITEM_GENERIC_SECRET,
      ^
    main.c:70:3: error: ‘gnome_keyring_memory_strdup’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring-memory.h:76): Use 'gcr_secure_memory_strdup' instead [-Werror=deprecated-declarations]
       secret = gnome_keyring_memory_strdup (found->secret);
       ^
    main.c:73:2: error: ‘gnome_keyring_found_list_free’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring.h:174) [-Werror=deprecated-declarations]
      gnome_keyring_found_list_free (found_list);
      ^
    main.c: In function ‘get_secrets’:
    main.c:131:4: error: ‘gnome_keyring_memory_strdup’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring-memory.h:76): Use 'gcr_secure_memory_strdup' instead [-Werror=deprecated-declarations]
        pw = gnome_keyring_memory_strdup (in_pw);
        ^
    main.c:138:3: error: ‘gnome_keyring_memory_free’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring-memory.h:70): Use 'gcr_secure_memory_free' instead [-Werror=deprecated-declarations]
       gnome_keyring_memory_free (pw);
       ^
    main.c:188:4: error: ‘gnome_keyring_memory_strdup’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring-memory.h:76): Use 'gcr_secure_memory_strdup' instead [-Werror=deprecated-declarations]
        *out_pw = gnome_keyring_memory_strdup (new_password);
        ^
    main.c: In function ‘main’:
    main.c:284:3: error: ‘gnome_keyring_memory_free’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring-memory.h:70): Use 'gcr_secure_memory_free' instead [-Werror=deprecated-declarations]
       gnome_keyring_memory_free (password);
       ^
    cc1: all warnings being treated as errors
    Makefile:475: recipe for target 'nm_l2tp_auth_dialog-main.o' failed
    make[2]: *** [nm_l2tp_auth_dialog-main.o] Error 1
    make[2]: Leaving directory '/tmp/yaourt-tmp-acgtyrant/aur-networkmanager-l2tp/src/NetworkManager-l2tp-0.9.8/auth-dialog'
    Makefile:523: recipe for target 'all-recursive' failed
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory '/tmp/yaourt-tmp-acgtyrant/aur-networkmanager-l2tp/src/NetworkManager-l2tp-0.9.8'
    Makefile:412: recipe for target 'all' failed
    make: *** [all] Error 2

Thank you!

**Comment by andredasilvapinto** [comment]
I have the same problem with debian jessie:

```
main.c: In function ‘keyring_lookup_secret’:
main.c:56:2: error: ‘gnome_keyring_find_itemsv_sync’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring.h:325): Use 'secret_service_search_sync' instead [-Werror=deprecated-declarations]
  ret = gnome_keyring_find_itemsv_sync (GNOME_KEYRING_ITEM_GENERIC_SECRET,
  ^
main.c:70:3: error: ‘gnome_keyring_memory_strdup’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring-memory.h:76): Use 'gcr_secure_memory_strdup' instead [-Werror=deprecated-declarations]
   secret = gnome_keyring_memory_strdup (found->secret);
   ^
main.c:73:2: error: ‘gnome_keyring_found_list_free’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring.h:174) [-Werror=deprecated-declarations]
  gnome_keyring_found_list_free (found_list);
  ^
main.c: In function ‘get_secrets’:
main.c:127:4: error: ‘gnome_keyring_memory_strdup’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring-memory.h:76): Use 'gcr_secure_memory_strdup' instead [-Werror=deprecated-declarations]
    pw = gnome_keyring_memory_strdup (in_pw);
    ^
main.c:134:3: error: ‘gnome_keyring_memory_free’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring-memory.h:70): Use 'gcr_secure_memory_free' instead [-Werror=deprecated-declarations]
   gnome_keyring_memory_free (pw);
   ^
main.c:184:4: error: ‘gnome_keyring_memory_strdup’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring-memory.h:76): Use 'gcr_secure_memory_strdup' instead [-Werror=deprecated-declarations]
    *out_pw = gnome_keyring_memory_strdup (new_password);
    ^
main.c: In function ‘main’:
main.c:280:3: error: ‘gnome_keyring_memory_free’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring-memory.h:70): Use 'gcr_secure_memory_free' instead [-Werror=deprecated-declarations]
   gnome_keyring_memory_free (password);
   ^
cc1: all warnings being treated as errors
Makefile:475: recipe for target 'nm_l2tp_auth_dialog-main.o' failed
make[2]: *** [nm_l2tp_auth_dialog-main.o] Error 1
make[2]: Leaving directory '/home/andre/tools/NetworkManager-l2tp/auth-dialog'
Makefile:523: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/andre/tools/NetworkManager-l2tp'
Makefile:412: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by seriyps** [comment]
Project development was moved to https://github.com/nm-l2tp/network-manager-l2tp
If you feel that this problem wasn't resolved, please, re-create this issue on this new project.
