### ISSUE TITLE
Unable to connect to Ivacy using L2TP/IPSec

### ISSUE THREAD

**Issue by monreal** [seriyps/NetworkManager-l2tp#18]
I am trying to connect to the Ivacy L2TP/IPSec VPN [1] but I am not able to get
past STATE_QUICK_I1. 

Tested with the following packages on Fedora 20:
NetworkManager-0.9.9.1-4.git20140319.fc20.x86_64
NetworkManager-l2tp-0.9.8.6-1.fc20.x86_64

[1] documentation for Mac OS X: https://ivacy.com/docs/support/mac_os_x_ipsec

$ sudo /usr/libexec/nm-l2tp-service
** Message: Use '213.232.200.180' as a gateway
** Message: Check port 1701
** Message: ipsec enable flag: yes
** Message: starting ipsec
Redirecting to: systemctl stop+start ipsec.service
002 listening for IKE messages
002 forgetting secrets
002 loading secrets from "/etc/ipsec.secrets"
002 forgetting secrets
002 loading secrets from "/etc/ipsec.secrets"
Warning: ignored obsolete keyword 'force_keepalive'
opening file: /var/run/nm-ipsec-l2tp.11425/ipsec.conf
debugging mode enabled
end of file /var/run/nm-ipsec-l2tp.11425/ipsec.conf
Warning: ignored obsolete keyword 'force_keepalive'
Loading conn nm-ipsec-l2tpd-11425
connection's  policy label: (null)
starter: case KH_DEFAULTROUTE: empty
loading named conns: nm-ipsec-l2tpd-11425
parse_src = 1, parse_gateway = 0, has_dst = 1
dst 213.232.200.180 via 192.168.178.1 dev wlp3s0 src 192.168.178.29
set addr: 192.168.178.29
conn: "nm-ipsec-l2tpd-11425" loopback=0
conn: "nm-ipsec-l2tpd-11425" labeled_ipsec=0
conn: "nm-ipsec-l2tpd-11425" policy_label=(null)
conn: "nm-ipsec-l2tpd-11425" modecfgdomain=(null)
conn: "nm-ipsec-l2tpd-11425" modecfgbanner=(null)
002 "nm-ipsec-l2tpd-11425": deleting connection
002 added connection description "nm-ipsec-l2tpd-11425"
002 "nm-ipsec-l2tpd-11425" #1: initiating Main Mode
104 "nm-ipsec-l2tpd-11425" #1: STATE_MAIN_I1: initiate
003 "nm-ipsec-l2tpd-11425" #1: received Vendor ID payload
[draft-ietf-ipsec-nat-t-ike-02_n]
003 "nm-ipsec-l2tpd-11425" #1: received Vendor ID payload [FRAGMENTATION
c0000000]
002 "nm-ipsec-l2tpd-11425" #1: enabling possible NAT-traversal with method
draft-ietf-ipsec-nat-t-ike-02/03
002 "nm-ipsec-l2tpd-11425" #1: transition from state STATE_MAIN_I1 to state
STATE_MAIN_I2
106 "nm-ipsec-l2tpd-11425" #1: STATE_MAIN_I2: sent MI2, expecting MR2
003 "nm-ipsec-l2tpd-11425" #1: received Vendor ID payload [Cisco-Unity]
003 "nm-ipsec-l2tpd-11425" #1: received Vendor ID payload [XAUTH]
003 "nm-ipsec-l2tpd-11425" #1: ignoring unknown Vendor ID payload
[d35dc78fd87d7e25953340cf0bbb5742]
003 "nm-ipsec-l2tpd-11425" #1: ignoring Vendor ID payload [Cisco VPN 3000
Series]
003 "nm-ipsec-l2tpd-11425" #1: NAT-Traversal: Result using
draft-ietf-ipsec-nat-t-ike-02/03: both are NATed
002 "nm-ipsec-l2tpd-11425" #1: Not sending INITIAL_CONTACT
002 "nm-ipsec-l2tpd-11425" #1: transition from state STATE_MAIN_I2 to state
STATE_MAIN_I3
108 "nm-ipsec-l2tpd-11425" #1: STATE_MAIN_I3: sent MI3, expecting MR3
003 "nm-ipsec-l2tpd-11425" #1: received Vendor ID payload [Dead Peer Detection]
002 "nm-ipsec-l2tpd-11425" #1: Main mode peer ID is ID_IPV4_ADDR:
'213.232.200.180'
002 "nm-ipsec-l2tpd-11425" #1: transition from state STATE_MAIN_I3 to state
STATE_MAIN_I4
004 "nm-ipsec-l2tpd-11425" #1: STATE_MAIN_I4: ISAKMP SA established
{auth=OAKLEY_PRESHARED_KEY cipher=oakley_3des_cbc_192 prf=oakley_sha
group=modp1024}
002 "nm-ipsec-l2tpd-11425" #2: initiating Quick Mode
PSK+ENCRYPT+UP+IKEv2ALLOW+SAREFTRACK+IKE_FRAG {using isakmp#1 msgid:8f828099
proposal=3DES(3)_192-SHA1(2)_160 pfsgroup=no-pfs}
117 "nm-ipsec-l2tpd-11425" #2: STATE_QUICK_I1: initiate
010 "nm-ipsec-l2tpd-11425" #2: STATE_QUICK_I1: retransmission; will wait 20s
for response
010 "nm-ipsec-l2tpd-11425" #2: STATE_QUICK_I1: retransmission; will wait 40s
for response

**Comment by seriyps** [comment]
Project development was moved to https://github.com/nm-l2tp/network-manager-l2tp
If you feel that this problem wasn't resolved, please, re-create this issue on this new project.
