### ISSUE TITLE
nm-l2tp-service: does not start ipsec service automatically

### ISSUE THREAD

**Issue by monreal** [seriyps/NetworkManager-l2tp#19]
While trying to set up an L2TP-based VPN I came across a connection problem
where there was no helpful message by the NetworkManager GUI component or
GNOME. I started the nm-l2tp-service manually and found this:

$ sudo /usr/libexec/nm-l2tp-service
** Message: Use '213.232.200.180' as a gateway
** Message: Check port 1701
** Message: ipsec enable flag: yes
** Message: starting ipsec
systemd: ipsec service is not running
whack: Pluto is not running (no "/var/run/pluto/pluto.ctl")
whack: Pluto is not running (no "/var/run/pluto/pluto.ctl")
Warning: ignored obsolete keyword 'force_keepalive'
connect(pluto_ctl) failed: No such file or directory
opening file: /var/run/nm-ipsec-l2tp.11976/ipsec.conf
debugging mode enabled
end of file /var/run/nm-ipsec-l2tp.11976/ipsec.conf
Warning: ignored obsolete keyword 'force_keepalive'
Loading conn nm-ipsec-l2tpd-11976
connection's  policy label: (null)
starter: case KH_DEFAULTROUTE: empty
loading named conns: nm-ipsec-l2tpd-11976
parse_src = 1, parse_gateway = 0, has_dst = 1
dst 213.232.200.180 via 192.168.178.1 dev wlp3s0 src 192.168.178.29
set addr: 192.168.178.29
conn: "nm-ipsec-l2tpd-11976" loopback=0
conn: "nm-ipsec-l2tpd-11976" labeled_ipsec=0
conn: "nm-ipsec-l2tpd-11976" policy_label=(null)
conn: "nm-ipsec-l2tpd-11976" modecfgdomain=(null)
conn: "nm-ipsec-l2tpd-11976" modecfgbanner=(null)
connect(pluto_ctl) failed: No such file or directory
whack: Pluto is not running (no "/var/run/pluto/pluto.ctl")
whack: Pluto is not running (no "/var/run/pluto/pluto.ctl")

I had to start the service "ipsec" manually. Interestingly, when the service is
running I see this in the logs:

Message: starting ipsec
Redirecting to: systemctl stop+start ipsec.service

It looks like NM should also try to start the service if it is not already
running.

**Comment by seriyps** [comment]
Project development was moved to https://github.com/nm-l2tp/network-manager-l2tp
If you feel that this problem wasn't resolved, please, re-create this issue on this new project.
