### ISSUE TITLE
vpn service failed to start

### ISSUE THREAD

**Issue by hilojack** [seriyps/NetworkManager-l2tp#2]
I've installed network-manager-l2tp-gnome.I add a vpn connection ,start it,and get such a error:
*The VPN connection "whatever" failed because vpn service failed to start*

Here is my debug info.Thanks in advance.

hilo@hilo-Rev-1-0:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04 LTS
Release:	12.04
Codename:	precise
hilo@hilo-Rev-1-0:~$ uname -a
Linux hilo-Rev-1-0 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
hilo@hilo-Rev-1-0:~$ apt-cache policy network-manager-l2tp xl2tpd ppp openswan
network-manager-l2tp:
  Installed: 0.9.4-0precise1
  Candidate: 0.9.4-0precise1
  Version table:
 *** 0.9.4-0precise1 0
        500 http://ppa.launchpad.net/seriy-pr/network-manager-l2tp/ubuntu/ precise/main amd64 Packages
        100 /var/lib/dpkg/status
xl2tpd:
  Installed: 1.3.1+dfsg-1
  Candidate: 1.3.1+dfsg-1
  Version table:
 *** 1.3.1+dfsg-1 0
        500 http://mirrors.sohu.com/ubuntu/ precise/universe amd64 Packages
        100 /var/lib/dpkg/status
ppp:
  Installed: 2.4.5-5ubuntu1
  Candidate: 2.4.5-5ubuntu1
  Version table:
 *** 2.4.5-5ubuntu1 0
        500 http://mirrors.sohu.com/ubuntu/ precise/main amd64 Packages
        100 /var/lib/dpkg/status
openswan:
  Installed: 1:2.6.37-1
  Candidate: 1:2.6.37-1
  Version table:
 *** 1:2.6.37-1 0
        500 http://mirrors.sohu.com/ubuntu/ precise/universe amd64 Packages
        100 /var/lib/dpkg/status

hilo@hilo-Rev-1-0:~$ sudo /usr/lib/NetworkManager/nm-l2tp-service --debug
** Message: nm-l2tp-service (version 0.9.4-0precise1) starting...
connection
	name : "connection"
	id : "SINA" (s)
	uuid : "c1e7e0bd-f613-452b-9f5d-517e44835108" (s)
	type : "vpn" (s)
	permissions : [] (sd)

	autoconnect : FALSE (s)
	timestamp : 0 (sd)
	read-only : FALSE (sd)
	zone : NULL (sd)
	master : NULL (sd)
	slave-type : NULL (sd)

vpn
	name : "vpn"
	service-type : "org.freedesktop.NetworkManager.l2tp" (s)
	user-name : "hilo" (s)
	data : [ { 'password-flags': 3 }, { 'ipsec-group-name': l2tp }, { 'ipsec-psk': ******* }, { 'user': xuehui1 }, { 'refuse-eap': yes }, { 'refuse-chap': yes }, { 'ipsec-enabled': yes }, { 'gateway': vpn.sina.com }, { 'refuse-mschap': yes }, { 'refuse-pap': yes }, ] (s)
	secrets : [ { 'password': **** }, ] (s)

ipv4
	name : "ipv4"
	method : "auto" (s)
	dns : [] (s)
	dns-search : [] (sd)
	addresses : [] (s)
	routes : [] (s)
	ignore-auto-routes : FALSE (sd)
	ignore-auto-dns : FALSE (sd)
	dhcp-client-id : NULL (sd)
	dhcp-send-hostname : TRUE (sd)
	dhcp-hostname : NULL (sd)
	never-default : FALSE (sd)
	may-fail : TRUE (sd)

** Message: Use '202.106.169.230' as a gateway
** Message: Check port 1701
** Message: ipsec enable flag: yes
** Message: starting ipsec
/usr/sbin/ipsec: unknown option `--listen' (perhaps command name was omitted?)

**Comment by seriyps** [comment]
Project development was moved to https://github.com/nm-l2tp/network-manager-l2tp
If you feel that this problem wasn't resolved, please, re-create this issue on this new project.
