### ISSUE TITLE
В данный момент плагин NetworkManager-l2tp невозможно собрать.

### ISSUE THREAD

**Issue by CoolAller** [seriyps/NetworkManager-l2tp#23]
Здравствуйте Сергей!

Пытался собрать ваш плагин для Debian. В настоящий момент собрать плагин без ошибок невозможно, из-за изменений внесенных в automake (подробнее здесь: http://www.gnu.org/software/automake/manual/html_node/Program-Variables.html), а именно старой переменной INCLUDES, которая сейчас переименована в AM_CPPFLAGS/_CPPFLAGS:

INCLUDES
 This does the same job as AM_CPPFLAGS (or any per-target _CPPFLAGS variable if it is used). It is an older name for the same functionality. This variable is deprecated; we suggest using AM_CPPFLAGS and per-target _CPPFLAGS instead. 

При выполнении ./autogen.sh выдает следующее сообщение:
auth-dialog/Makefile.am:1: warning: ‘INCLUDES’ is the old name for ‘AM_CPPFLAGS’ (or ‘*_CPPFLAGS’)
auth-dialog/Makefile.am: installing ‘./depcomp’
properties/Makefile.am:4: warning: ‘INCLUDES’ is the old name for ‘AM_CPPFLAGS’ (or ‘*_CPPFLAGS’)
src/Makefile.am:1: warning: ‘INCLUDES’ is the old name for ‘AM_CPPFLAGS’ (or ‘*_CPPFLAGS’)
auth-dialog/Makefile.am:1: warning: ‘INCLUDES’ is the old name for ‘AM_CPPFLAGS’ (or ‘*_CPPFLAGS’)
properties/Makefile.am:4: warning: ‘INCLUDES’ is the old name for ‘AM_CPPFLAGS’ (or ‘*_CPPFLAGS’)
src/Makefile.am:1: warning: ‘INCLUDES’ is the old name for ‘AM_CPPFLAGS’ (or ‘*_CPPFLAGS’)

Подозреваю, что старая переменная автоматически не заменяется automake на новую и просто выводится сообщение об ошибке.

Команда ./configure отрабатывает без ошибок. (Насколько я понял в файле README.ubuntu содержатся замечания только для Ubuntu, для Debian ./configure запускается без дополнительных аргументов?) На всякий случай напишу, что в настоящий момент, пакет openswan уже выпилен из многих дистрибутивов, а IPSec все еще нужен, ваш плагин совместим с racoon?

При попытке выполнить make выводятся следующие ошибки:
main.c: In function ‘keyring_lookup_secret’:
main.c:56:2: error: ‘gnome_keyring_find_itemsv_sync’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring.h:325): Use 'secret_service_search_sync' instead [-Werror=deprecated-declarations]
  ret = gnome_keyring_find_itemsv_sync (GNOME_KEYRING_ITEM_GENERIC_SECRET,
  ^
main.c:70:3: error: ‘gnome_keyring_memory_strdup’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring-memory.h:76): Use 'gcr_secure_memory_strdup' instead [-Werror=deprecated-declarations]
   secret = gnome_keyring_memory_strdup (found->secret);
   ^
main.c:73:2: error: ‘gnome_keyring_found_list_free’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring.h:174) [-Werror=deprecated-declarations]
  gnome_keyring_found_list_free (found_list);
  ^
main.c: In function ‘get_secrets’:
main.c:127:4: error: ‘gnome_keyring_memory_strdup’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring-memory.h:76): Use 'gcr_secure_memory_strdup' instead [-Werror=deprecated-declarations]
    pw = gnome_keyring_memory_strdup (in_pw);
    ^
main.c:134:3: error: ‘gnome_keyring_memory_free’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring-memory.h:70): Use 'gcr_secure_memory_free' instead [-Werror=deprecated-declarations]
   gnome_keyring_memory_free (pw);
   ^
main.c:184:4: error: ‘gnome_keyring_memory_strdup’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring-memory.h:76): Use 'gcr_secure_memory_strdup' instead [-Werror=deprecated-declarations]
    *out_pw = gnome_keyring_memory_strdup (new_password);
    ^
main.c: In function ‘main’:
main.c:280:3: error: ‘gnome_keyring_memory_free’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring-memory.h:70): Use 'gcr_secure_memory_free' instead [-Werror=deprecated-declarations]
   gnome_keyring_memory_free (password);
   ^
cc1: all warnings being treated as errors
make[2]: *** [nm_l2tp_auth_dialog-main.o] Error 1
make[2]: Leaving directory `/home/user/Desktop/NetworkManager-l2tp-master/auth-dialog'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/user/Desktop/NetworkManager-l2tp-master'
make: *** [all] Error 2
Подозреваю, что проблема с make связана с пакетом libgnome-keyring-dev (в данный момент актуальная версия libgnome-keyring-dev 3.12.0-1), который был установлен для удовлетворения зависимости при компиляции - требовался gnome-keyring-1.

Интересно узнать, вы все еще планируете поддерживать разработку плагина L2TP для NM?

**Comment by seriyps** [comment]
Project development was moved to https://github.com/nm-l2tp/network-manager-l2tp
If you feel that this problem wasn't resolved, please, re-create this issue on this new project.
