### ISSUE TITLE
В Ubuntu до сих пор нельзя штатными средствами подконектиться к l2tp?

### ISSUE THREAD

**Issue by pashinin** [seriyps/NetworkManager-l2tp#24]
К московскому Билайну например?
У меня эта проблема была очень давно, все это время юзал xl2tpd.
Просто если до сих пор с этим беда - протолкните, плз, эту надструйку для NM как-нибудь в основной код (что б в ОС был).

**Comment by seriyps** [comment]
Project development was moved to https://github.com/nm-l2tp/network-manager-l2tp
If you feel that this problem wasn't resolved, please, re-create this issue on this new project.
