### ISSUE TITLE
Does not work with mppe in Mageia Linux

### ISSUE THREAD

**Issue by glixx** [seriyps/NetworkManager-l2tp#30]
It's the same bug https://bugs.mageia.org/show_bug.cgi?id=2894

There is problem for NM with mppe.
For example, 128 encription in Mageia now:
mppe required, stateless, no40, no56
but NM understands only:
require-mppe-128

**Comment by seriyps** [comment]
Project development was moved to https://github.com/nm-l2tp/network-manager-l2tp
If you feel that this problem wasn't resolved, please, re-create this issue on this new project.
