### ISSUE TITLE
Change of MTU and MRU

### ISSUE THREAD

**Issue by kometchtech** [seriyps/NetworkManager-l2tp#31]
For stability during VPN connection, what does not will be able to explicitly set the MTU size?
If left 1400, because the slightly problem is out to browse the Web.

https://lists.openswan.org/pipermail/users/2011-April/020387.html

$ sudo apt-cache policy network-manager-l2tp 
network-manager-l2tp:
  Installed: 0.9.8.5-0utopic1
  Candidate: 0.9.8.5-0utopic1
  Version table:
 *** 0.9.8.5-0utopic1 0
        500 http://ppa.launchpad.net/seriy-pr/network-manager-l2tp/ubuntu/ utopic/main amd64 Packages
        100 /var/lib/dpkg/status

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.10
Release:	14.10
Codename:	utopic

$ uname -a
Linux X61s 3.16.0-29-generic #39-Ubuntu SMP Mon Dec 15 22:27:29 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dkosovic** [comment]
I've created a new nm_0.9 fork which allows setting the MTU and MRU in the GUI. The fork is here :
   https://github.com/dkosovic/NetworkManager-l2tp/tree/nm_0.9

It contains many other bug fixes.

I've also requested a pull request.

**Comment by seriyps** [comment]
Project development was moved to https://github.com/nm-l2tp/network-manager-l2tp
If you feel that this problem wasn't resolved, please, re-create this issue on this new project.
