### ISSUE TITLE
debian/ directory available in Git?

### ISSUE THREAD

**Issue by voltagex** [seriyps/NetworkManager-l2tp#32]
Hi,
Is the source for the Debian packaging available somewhere?

**Comment by seriyps** [comment]
Hi,
no, currently it's not. But I think I'll publish them in current repository's branches (one branch for each supported Ubuntu release).

For now you can download them from https://launchpad.net/~seriy-pr/+archive/ubuntu/network-manager-l2tp/+packages .

You may expand items in package list and download `network-manager-l2tp_<version>.debian.tar.xz` tarball.

================
![image](https://cloud.githubusercontent.com/assets/422014/5736445/ed35e23c-9be6-11e4-8ee4-60f8dbdd2c6b.png)
================
