### ISSUE TITLE
No connection established

### ISSUE THREAD

**Issue by wavetydesigns** [seriyps/NetworkManager-l2tp#33]
Cannot get connected to VPN, stops at "loading named conns: ..." then fails. Brand new install of 14.04...Here are the logs...

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

uname -a
Linux ComputerName 3.16.0-31-generic #41~14.04.1-Ubuntu SMP Wed Feb 11 19:30:13 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

tail -f -n 0 /var/log/syslog
Mar  1 22:40:24 ComputerName NetworkManager[870]: <info> VPN service 'l2tp' appeared; activating connections
Mar  1 22:40:33 ComputerName NetworkManager[870]: <info> VPN plugin state changed: starting (3)
Mar  1 22:40:58 ComputerName NetworkManager[870]: <info> VPN connection 'Connection' (Connect) reply received.
Mar  1 22:40:58 ComputerName NetworkManager[870]: <warn> VPN connection 'Connection' failed to connect: 'Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.'.
Mar  1 22:41:23 ComputerName NetworkManager[870]: <warn> error disconnecting VPN: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

sudo /usr/lib/NetworkManager/nm-l2tp-service --debug
** Message: nm-l2tp-service (version 0.9.8.5-0saucy1) starting...
connection
	name : "connection"
	id : "Connection" (s)
	uuid : "4719d417-6659-4eb7-8bfc-010118946a14" (s)
	type : "vpn" (s)
	permissions : [] (sd)
	autoconnect : FALSE (s)
	timestamp : 0 (sd)
	read-only : FALSE (sd)
	zone : NULL (sd)
	master : NULL (sd)
	slave-type : NULL (sd)
	secondaries : [] (sd)

vpn
	name : "vpn"
	service-type : "org.freedesktop.NetworkManager.l2tp" (s)
	user-name : "xxxxx" (s)
	data : [ { 'lcp-echo-interval': 30 }, { 'password-flags': 3 }, { 'ipsec-group-name': GroupVPN }, { 'ipsec-psk': xxxxxxxx }, { 'user': xxxxx }, { 'refuse-eap': yes }, { 'refuse-chap': yes }, { 'ipsec-enabled': yes }, { 'lcp-echo-failure': 5 }, { 'gateway': xxx.xx.xxx.xxx }, { 'refuse-mschap': yes }, { 'refuse-pap': yes }, ] (s)
	secrets : [ { 'password': xxxxxxxxxx }, ] (s)

ipv4
	name : "ipv4"
	method : "auto" (s)
	dns : [134284554 (x.x.x.x)] (s)
	dns-search : ['xxxxxxx.xxx'] (s)
	addresses : [] (s)
	routes : [] (s)
	ignore-auto-routes : FALSE (sd)
	ignore-auto-dns : FALSE (sd)
	dhcp-client-id : NULL (sd)
	dhcp-send-hostname : TRUE (sd)
	dhcp-hostname : NULL (sd)
	never-default : FALSE (sd)
	may-fail : TRUE (sd)

** Message: Check port 1701
** Message: ipsec enable flag: yes
** Message: starting ipsec
002 listening for IKE messages
002 forgetting secrets
002 loading secrets from "/etc/ipsec.secrets"
002 added connection description "nm-ipsec-l2tpd-19482"
opening file: /var/run/nm-ipsec-l2tp.19482/ipsec.conf
debugging mode enabled
end of file /var/run/nm-ipsec-l2tp.19482/ipsec.conf
Loading conn nm-ipsec-l2tpd-19482
default route is: local.ip.address
default nexthop is: local.router.ip
002 "nm-ipsec-l2tpd-19482": deleting connection
002 added connection description "nm-ipsec-l2tpd-19482"
loading named conns: nm-ipsec-l2tpd-19482
...

Thank you.

**Comment by wavetydesigns** [comment]
*bump*
Any ideas?

**Comment by ndorf** [comment]
Do you get this every single time or does it eventually work?

**Comment by wavetydesigns** [comment]
Nathan,

I get this every time.  Odd thing is, I can set everything up manually and connect just fine.  Difference being that I can set the rightid to an actual ip address not an @ alias.

**Comment by seriyps** [comment]
Project development was moved to https://github.com/nm-l2tp/network-manager-l2tp
If you feel that this problem wasn't resolved, please, re-create this issue on this new project.
