### ISSUE TITLE
we require peer to have ID 'X.X.X.X', but peer declares 'Y.Y.Y.Y'

### ISSUE THREAD

**Issue by drnextgis** [seriyps/NetworkManager-l2tp#36]
При попытке подключения получал вот такое сообщение:

```
we require peer to have ID '195.210.50.155', but peer declares '10.10.3.1'
```

Ошибка эта насколько я понял возникает из-за того, что значение `right` и `rightid` не совпадают. Чтобы поменять `rightid` согласно [коду](https://github.com/seriyps/NetworkManager-l2tp/blob/master/src/nm-l2tp-service.c#L1122) надо задать значение `Gateway ID`, но это значение идет в `rightid` не в исходном виде, а дополняется вначале символом `@`, поэтому указание нужного IP в `Gateway ID` тоже не помогло. Пришлось убрать `@`, пересобрать модуль и тогда всё заработало.

**Comment by seriyps** [comment]
Project development was moved to https://github.com/nm-l2tp/network-manager-l2tp
If you feel that this problem wasn't resolved, please, re-create this issue on this new project.
