### ISSUE TITLE
Denpendecy on 

### ISSUE THREAD

**Issue by pishty1** [seriyps/NetworkManager-l2tp#40]
hello,
am running autogen.sh but its breaking because its dependent on NetworkManager1.1.0, can anyone tell me where i can get this from, am running Kali linux 2.0

**Comment by dkosovic** [comment]
NetworkManager 1.1.0 is basically a beta release of 1.2.

nm-1-0 branch no longer builds with NetworkManager-1.0.x as it is contaminated with NetworkManager 1.2 configure script and code updates. The master branch no longer builds either, but that is to be expected.

I've created a new nm_0.9 branch here :
   https://github.com/dkosovic/NetworkManager-l2tp/tree/nm_0.9
it still builds with NetworkManager-1.0 and contains many bug fixes.

**Comment by seriyps** [comment]
Project development was moved to https://github.com/nm-l2tp/network-manager-l2tp
If you feel that this problem wasn't resolved, please, re-create this issue on this new project.
