### ISSUE TITLE
Problem with ipsec arguments

### ISSUE THREAD

**Issue by kentone** [seriyps/NetworkManager-l2tp#41]
Hi,

My name is Guillermo, im not programmer, im a sysadmin from Spain. Using
the last branch of "networkmanager-l2tp" on Arch Linux I detected an
error on nm-l2tp-service.c.

The parameter --verbose is not compatibe with my version of the command
"ipsec" provided by the package "openswan". This means that the whole
command will fail.

I checked the lines on the source code and found the error on the lines
of nm-l2tp-service.c:

976
981

Hope I help. Cheers.

**Comment by seriyps** [comment]
Project development was moved to https://github.com/nm-l2tp/network-manager-l2tp
If you feel that this problem wasn't resolved, please, re-create this issue on this new project.
