### ISSUE TITLE
Don't require a password when authentication with certificates

### ISSUE THREAD

**Issue by frenetic1** [seriyps/NetworkManager-l2tp#44]
Apparently there was always a password leftover when I was testing it. This patch removes the requirement for a password when using certificates.
[cert_auth_without_pwd.txt](https://github.com/seriyps/NetworkManager-l2tp/files/60630/cert_auth_without_pwd.txt)

**Comment by seriyps** [comment]
Project development was moved to https://github.com/nm-l2tp/network-manager-l2tp
If you feel that this problem wasn't resolved, please, re-create this issue on this new project.
