### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by ghost** [seriyps/NetworkManager-l2tp#46]
main.c: In function ‘keyring_lookup_secret’:
main.c:56:2: error: ‘gnome_keyring_find_itemsv_sync’ is deprecated: Use 'secret_service_search_sync' instead [-Werror=deprecated-declarations]
  ret = gnome_keyring_find_itemsv_sync (GNOME_KEYRING_ITEM_GENERIC_SECRET,
  ^~~
In file included from main.c:33:0:
/usr/include/gnome-keyring-1/gnome-keyring.h:325:20: note: declared here
 GnomeKeyringResult gnome_keyring_find_itemsv_sync (GnomeKeyringItemType        type,
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
main.c:70:3: error: ‘gnome_keyring_memory_strdup’ is deprecated: Use 'gcr_secure_memory_strdup' instead [-Werror=deprecated-declarations]
   secret = gnome_keyring_memory_strdup (found->secret);
   ^~~~~~

**Comment by dkosovic** [comment]
GNOME keyring has be superseded by libsecret.

Try the code from the newer repo instead:
https://github.com/nm-l2tp/network-manager-l2tp

I accidently saw your issue on GitHub while looking for something else.

**Comment by ndorf** [comment]
Development has moved to  https://github.com/nm-l2tp/network-manager-l2tp as above.
