### ISSUE TITLE
build fails due tot not checking returned status  on system().

### ISSUE THREAD

**Issue by noci2012** [seriyps/NetworkManager-l2tp#48]
Build fails with gcc: 

nm-l2tp-service.c: In function ‘nm_l2tp_stop_ipsec’:
nm-l2tp-service.c:928:3: error: ignoring return value of ‘system’, declared with attribute warn_unused_result [-Werror=unused-result]
   system (cmdbuf);
   ^

gcc (Gentoo 5.4.0-r3 p1.3, pie-0.6.5) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by ndorf** [comment]
This repo is obsolete, active development is at https://github.com/nm-l2tp/network-manager-l2tp
