### ISSUE TITLE
how to solve this problem.

### ISSUE THREAD

**Issue by Analee0418** [seriyps/NetworkManager-l2tp#51]
checking for pid_t... yes
checking whether time.h and sys/time.h may both be included... yes
checking whether gcc needs -traditional... no
checking for working memcmp... yes
checking for select... yes
checking for socket... yes
checking for uname... yes
./configure: line 12501: syntax error near unexpected token `0.35'
./configure: line 12501: `IT_PROG_INTLTOOL(0.35)'

**Comment by seriyps** [comment]
Hi. This repository is not maintained anymore. Please, check this one https://github.com/nm-l2tp/network-manager-l2tp
