### ISSUE TITLE
Can not build networkmanager-l2tp

### ISSUE THREAD

**Issue by NgoHuy** [seriyps/NetworkManager-l2tp#6]
I use Archlinux and I have new glib2, when I built networkmanager-l2tp, it said

`nm-l2tp-service.c: In function ‘main’:
nm-l2tp-service.c:1637:2: error: ‘g_type_init’ is deprecated (declared at /usr/include/glib-2.0/gobject/gtype.h:669) [-Werror=deprecated-declarations]
  g_type_init ();`

and it's terminated.

**Comment by seriyps** [comment]
Project development was moved to https://github.com/nm-l2tp/network-manager-l2tp
If you feel that this problem wasn't resolved, please, re-create this issue on this new project.
