### ISSUE TITLE
Could Not Build In Chakra-Linux

### ISSUE THREAD

**Issue by HougeLangley** [seriyps/NetworkManager-l2tp#8]
[hougelangley@chakra-laptop ~]$ cd Source/NetworkManager-l2tp/
[hougelangley@chakra-laptop NetworkManager-l2tp]$ ls
auth-dialog/  properties/  autogen.sh*   COPYING                                     NEWS                  nm-l2tp-service.name.in
m4/           src/         ChangeLog     gnome-mime-application-x-l2tp-settings.png  nm-l2tp.desktop.in    README
po/           AUTHORS      configure.ac  Makefile.am                                 nm-l2tp-service.conf  README.ubutntu
[hougelangley@chakra-laptop NetworkManager-l2tp]$ ./autogen.sh 
main::scan_file() called too early to check prototype at /usr/bin/aclocal line 621.
libtoolize: putting auxiliary files in `.'.
libtoolize: linking file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: linking file `m4/libtool.m4'
libtoolize: linking file `m4/ltoptions.m4'
libtoolize: linking file `m4/ltsugar.m4'
libtoolize: linking file `m4/ltversion.m4'
libtoolize: linking file `m4/lt~obsolete.m4'
main::scan_file() called too early to check prototype at /usr/bin/aclocal line 621.
configure.ac:15: installing `./compile'
configure.ac:17: installing `./config.guess'
configure.ac:17: installing `./config.sub'
configure.ac:4: installing `./install-sh'
configure.ac:4: installing `./missing'
auth-dialog/Makefile.am: installing `./depcomp'
main::scan_file() called too early to check prototype at /usr/bin/aclocal line 621.
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking whether gcc and cc understand -c and -o together... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for ANSI C header files... (cached) yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking paths.h usability... yes
checking paths.h presence... yes
checking for paths.h... yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for unistd.h... (cached) yes
checking pppd/pppd.h usability... yes
checking pppd/pppd.h presence... yes
checking for pppd/pppd.h... yes
checking for mode_t... yes
checking for pid_t... yes
checking whether time.h and sys/time.h may both be included... yes
checking whether gcc needs -traditional... no
checking for working memcmp... yes
checking for select... yes
checking for socket... yes
checking for uname... yes
checking whether NLS is requested... yes
checking for intltool >= 0.35... 0.50.2 found
checking for intltool-update... /usr/bin/intltool-update
checking for intltool-merge... /usr/bin/intltool-merge
checking for intltool-extract... /usr/bin/intltool-extract
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for perl... /usr/bin/perl
checking for perl >= 5.8.1... 5.18.0
checking for XML::Parser... ok
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking for LC_MESSAGES... yes
checking libintl.h usability... yes
checking libintl.h presence... yes
checking for libintl.h... yes
checking for ngettext in libc... yes
checking for dgettext in libc... yes
checking for bind_textdomain_codeset... yes
checking for msgfmt... (cached) /usr/bin/msgfmt
checking for dcgettext... yes
checking if msgfmt accepts -c... yes
checking for gmsgfmt... (cached) /usr/bin/msgfmt
checking for xgettext... (cached) /usr/bin/xgettext
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for GTHREAD... yes
checking for DBUS... yes
checking for NM... yes
checking for GTK... yes
checking for GNOMEKEYRING... yes
checking for more warnings... yes
checking whether gcc understands -Wshadow... yes
checking whether gcc understands -Wmissing-declarations... yes
checking whether gcc understands -Wmissing-prototypes... yes
checking whether gcc understands -Wdeclaration-after-statement... yes
checking whether gcc understands -Wstrict-prototypes... yes
checking whether gcc understands -Wfloat-equal... yes
checking whether gcc understands -Wno-unused-parameter... yes
checking whether gcc understands -Wno-sign-compare... yes
checking whether gcc understands -fno-strict-aliasing... yes
checking whether gcc understands -Wno-unused-but-set-variable... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating auth-dialog/Makefile
config.status: creating properties/Makefile
config.status: creating po/Makefile.in
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing default-1 commands
config.status: executing po/stamp-it commands
[hougelangley@chakra-laptop NetworkManager-l2tp]$ make -j4
(CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /home/hougelangley/Source/NetworkManager-l2tp/missing --run autoheader)
rm -f stamp-h1
touch config.h.in
cd . && /bin/sh ./config.status config.h
config.status: creating config.h
config.status: config.h is unchanged
make  all-recursive
make[1]: 进入目录“/home/hougelangley/Source/NetworkManager-l2tp”
Making all in src
make[2]: 进入目录“/home/hougelangley/Source/NetworkManager-l2tp/src”
dbus-binding-tool --prefix=nm_l2tp_pppd_service --mode=glib-server --output=nm-l2tp-pppd-service-glue.h ../src/nm-l2tp-pppd-service.xml
make  all-am
make[3]: 进入目录“/home/hougelangley/Source/NetworkManager-l2tp/src”
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I.. -I..   -I/usr/include/NetworkManager -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/libnm-glib     -Wall -std=gnu89 -g -O2 -Wshadow -Wmissing-declarations -Wmissing-prototypes -Wdeclaration-after-statement -Wstrict-prototypes -Wfloat-equal -Wno-unused-parameter -Wno-sign-compare -fno-strict-aliasing -Wno-unused-but-set-variable -Werror -MT nm_l2tp_pppd_plugin_la-nm-l2tp-pppd-plugin.lo -MD -MP -MF .deps/nm_l2tp_pppd_plugin_la-nm-l2tp-pppd-plugin.Tpo -c -o nm_l2tp_pppd_plugin_la-nm-l2tp-pppd-plugin.lo `test -f 'nm-l2tp-pppd-plugin.c' || echo './'`nm-l2tp-pppd-plugin.c
depbase=`echo nm-l2tp-service.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I.. -I..  -pthread -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include   -I/usr/include/NetworkManager -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/libnm-glib   -DG_DISABLE_DEPRECATED -DBINDIR=\"/usr/local/bin\" -DPREFIX=\""/usr/local"\" -DSYSCONFDIR=\""/usr/local/etc"\" -DNM_VERSION="\"0.9.8.0\"" -DLIBDIR=\""/usr/local/lib"\" -DLIBEXECDIR=\""/usr/local/libexec"\" -DLOCALSTATEDIR=\""/usr/local/var"\" -DDATADIR=\"/usr/local/share\" -DNM_L2TP_LOCALEDIR=\"/usr/local/share/locale\" -DPLUGINDIR=\"/usr/local/lib/pppd/2.4.5\"    -Wall -std=gnu89 -g -O2 -Wshadow -Wmissing-declarations -Wmissing-prototypes -Wdeclaration-after-statement -Wstrict-prototypes -Wfloat-equal -Wno-unused-parameter -Wno-sign-compare -fno-strict-aliasing -Wno-unused-but-set-variable -Werror -MT nm-l2tp-service.o -MD -MP -MF $depbase.Tpo -c -o nm-l2tp-service.o nm-l2tp-service.c &&\
mv -f $depbase.Tpo $depbase.Po
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I.. -I/usr/include/NetworkManager -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/libnm-glib -Wall -std=gnu89 -g -O2 -Wshadow -Wmissing-declarations -Wmissing-prototypes -Wdeclaration-after-statement -Wstrict-prototypes -Wfloat-equal -Wno-unused-parameter -Wno-sign-compare -fno-strict-aliasing -Wno-unused-but-set-variable -Werror -MT nm_l2tp_pppd_plugin_la-nm-l2tp-pppd-plugin.lo -MD -MP -MF .deps/nm_l2tp_pppd_plugin_la-nm-l2tp-pppd-plugin.Tpo -c nm-l2tp-pppd-plugin.c  -fPIC -DPIC -o .libs/nm_l2tp_pppd_plugin_la-nm-l2tp-pppd-plugin.o
In file included from /usr/lib/glib-2.0/include/glibconfig.h:9:0,
                 from /usr/include/glib-2.0/glib/gtypes.h:34,
                 from /usr/include/glib-2.0/glib/galloca.h:34,
                 from /usr/include/glib-2.0/glib.h:32,
                 from /usr/include/glib-2.0/glib/gi18n.h:23,
                 from nm-l2tp-service.c:51:
nm-l2tp-service.c: 在函数‘nm_l2tp_ppp_service_get_type’中:
/usr/include/glib-2.0/glib/gmacros.h:162:53: 错误：typedef ‘_GStaticAssertCompileTimeAssertion_0’ locally defined but not used [-Werror=unused-local-typedefs]
 #define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1]
                                                     ^
/usr/include/glib-2.0/glib/gmacros.h:159:47: 附注：in definition of macro ‘G_PASTE_ARGS’
 #define G_PASTE_ARGS(identifier1,identifier2) identifier1 ## identifier2
                                               ^
/usr/include/glib-2.0/glib/gmacros.h:162:44: 附注：in expansion of macro ‘G_PASTE’
 #define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1]
                                            ^
/usr/include/glib-2.0/glib/gthread.h:234:5: 附注：in expansion of macro ‘G_STATIC_ASSERT’
     G_STATIC_ASSERT (sizeof *(location) == sizeof (gpointer));       \
     ^
/usr/include/glib-2.0/gobject/gtype.h:1463:7: 附注：in expansion of macro ‘g_once_init_enter’
   if (g_once_init_enter (&g_define_type_id__volatile))  \
       ^
/usr/include/glib-2.0/gobject/gtype.h:1387:60: 附注：in expansion of macro ‘_G_DEFINE_TYPE_EXTENDED_BEGIN’
 #define G_DEFINE_TYPE_EXTENDED(TN, t_n, T_P, _f_, _C_)     _G_DEFINE_TYPE_EXTENDED_BEGIN (TN, t_n, T_P, _f_) {_C_;} _G_DEFINE_TYPE_EXTENDED_END()
                                                            ^
/usr/include/glib-2.0/gobject/gtype.h:1279:43: 附注：in expansion of macro ‘G_DEFINE_TYPE_EXTENDED’
 #define G_DEFINE_TYPE(TN, t_n, T_P)       G_DEFINE_TYPE_EXTENDED (TN, t_n, T_P, 0, {})
                                           ^
nm-l2tp-service.c:97:1: 附注：in expansion of macro ‘G_DEFINE_TYPE’
 G_DEFINE_TYPE (NML2tpPppService, nm_l2tp_ppp_service, G_TYPE_OBJECT);
 ^
/usr/include/glib-2.0/glib/gmacros.h:162:53: 错误：typedef ‘_GStaticAssertCompileTimeAssertion_1’ locally defined but not used [-Werror=unused-local-typedefs]
 #define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1]
                                                     ^
/usr/include/glib-2.0/glib/gmacros.h:159:47: 附注：in definition of macro ‘G_PASTE_ARGS’
 #define G_PASTE_ARGS(identifier1,identifier2) identifier1 ## identifier2
                                               ^
/usr/include/glib-2.0/glib/gmacros.h:162:44: 附注：in expansion of macro ‘G_PASTE’
 #define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1]
                                            ^
/usr/include/glib-2.0/glib/gatomic.h:136:5: 附注：in expansion of macro ‘G_STATIC_ASSERT’
     G_STATIC_ASSERT (sizeof *(atomic) == sizeof (gpointer));                 \
     ^
/usr/include/glib-2.0/glib/gthread.h:236:7: 附注：in expansion of macro ‘g_atomic_pointer_get’
     (!g_atomic_pointer_get (location) &&                             \
       ^
/usr/include/glib-2.0/gobject/gtype.h:1463:7: 附注：in expansion of macro ‘g_once_init_enter’
   if (g_once_init_enter (&g_define_type_id__volatile))  \
       ^
/usr/include/glib-2.0/gobject/gtype.h:1387:60: 附注：in expansion of macro ‘_G_DEFINE_TYPE_EXTENDED_BEGIN’
 #define G_DEFINE_TYPE_EXTENDED(TN, t_n, T_P, _f_, _C_)     _G_DEFINE_TYPE_EXTENDED_BEGIN (TN, t_n, T_P, _f_) {_C_;} _G_DEFINE_TYPE_EXTENDED_END()
                                                            ^
/usr/include/glib-2.0/gobject/gtype.h:1279:43: 附注：in expansion of macro ‘G_DEFINE_TYPE_EXTENDED’
 #define G_DEFINE_TYPE(TN, t_n, T_P)       G_DEFINE_TYPE_EXTENDED (TN, t_n, T_P, 0, {})
                                           ^
nm-l2tp-service.c:97:1: 附注：in expansion of macro ‘G_DEFINE_TYPE’
 G_DEFINE_TYPE (NML2tpPppService, nm_l2tp_ppp_service, G_TYPE_OBJECT);
 ^
/usr/include/glib-2.0/glib/gmacros.h:162:53: 错误：typedef ‘_GStaticAssertCompileTimeAssertion_2’ locally defined but not used [-Werror=unused-local-typedefs]
 #define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1]
                                                     ^
/usr/include/glib-2.0/glib/gmacros.h:159:47: 附注：in definition of macro ‘G_PASTE_ARGS’
 #define G_PASTE_ARGS(identifier1,identifier2) identifier1 ## identifier2
                                               ^
/usr/include/glib-2.0/glib/gmacros.h:162:44: 附注：in expansion of macro ‘G_PASTE’
 #define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1]
                                            ^
/usr/include/glib-2.0/glib/gthread.h:241:5: 附注：in expansion of macro ‘G_STATIC_ASSERT’
     G_STATIC_ASSERT (sizeof *(location) == sizeof (gpointer));       \
     ^
/usr/include/glib-2.0/gobject/gtype.h:1477:7: 附注：in expansion of macro ‘g_once_init_leave’
       g_once_init_leave (&g_define_type_id__volatile, g_define_type_id); \
       ^
/usr/include/glib-2.0/gobject/gtype.h:1387:117: 附注：in expansion of macro ‘_G_DEFINE_TYPE_EXTENDED_END’
 #define G_DEFINE_TYPE_EXTENDED(TN, t_n, T_P, _f_, _C_)     _G_DEFINE_TYPE_EXTENDED_BEGIN (TN, t_n, T_P, _f_) {_C_;} _G_DEFINE_TYPE_EXTENDED_END()
                                                                                                                     ^
/usr/include/glib-2.0/gobject/gtype.h:1279:43: 附注：in expansion of macro ‘G_DEFINE_TYPE_EXTENDED’
 #define G_DEFINE_TYPE(TN, t_n, T_P)       G_DEFINE_TYPE_EXTENDED (TN, t_n, T_P, 0, {})
                                           ^
nm-l2tp-service.c:97:1: 附注：in expansion of macro ‘G_DEFINE_TYPE’
 G_DEFINE_TYPE (NML2tpPppService, nm_l2tp_ppp_service, G_TYPE_OBJECT);
 ^
nm-l2tp-service.c: 在函数‘nm_l2tp_plugin_get_type’中:
/usr/include/glib-2.0/glib/gmacros.h:162:53: 错误：typedef ‘_GStaticAssertCompileTimeAssertion_3’ locally defined but not used [-Werror=unused-local-typedefs]
 #define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1]
                                                     ^
/usr/include/glib-2.0/glib/gmacros.h:159:47: 附注：in definition of macro ‘G_PASTE_ARGS’
 #define G_PASTE_ARGS(identifier1,identifier2) identifier1 ## identifier2
                                               ^
/usr/include/glib-2.0/glib/gmacros.h:162:44: 附注：in expansion of macro ‘G_PASTE’
 #define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1]
                                            ^
/usr/include/glib-2.0/glib/gthread.h:234:5: 附注：in expansion of macro ‘G_STATIC_ASSERT’
     G_STATIC_ASSERT (sizeof *(location) == sizeof (gpointer));       \
     ^
/usr/include/glib-2.0/gobject/gtype.h:1463:7: 附注：in expansion of macro ‘g_once_init_enter’
   if (g_once_init_enter (&g_define_type_id__volatile))  \
       ^
/usr/include/glib-2.0/gobject/gtype.h:1387:60: 附注：in expansion of macro ‘_G_DEFINE_TYPE_EXTENDED_BEGIN’
 #define G_DEFINE_TYPE_EXTENDED(TN, t_n, T_P, _f_, _C_)     _G_DEFINE_TYPE_EXTENDED_BEGIN (TN, t_n, T_P, _f_) {_C_;} _G_DEFINE_TYPE_EXTENDED_END()
                                                            ^
/usr/include/glib-2.0/gobject/gtype.h:1279:43: 附注：in expansion of macro ‘G_DEFINE_TYPE_EXTENDED’
 #define G_DEFINE_TYPE(TN, t_n, T_P)       G_DEFINE_TYPE_EXTENDED (TN, t_n, T_P, 0, {})
                                           ^
nm-l2tp-service.c:352:1: 附注：in expansion of macro ‘G_DEFINE_TYPE’
 G_DEFINE_TYPE (NML2tpPlugin, nm_l2tp_plugin, NM_TYPE_VPN_PLUGIN);
 ^
/usr/include/glib-2.0/glib/gmacros.h:162:53: 错误：typedef ‘_GStaticAssertCompileTimeAssertion_4’ locally defined but not used [-Werror=unused-local-typedefs]
 #define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1]
                                                     ^
/usr/include/glib-2.0/glib/gmacros.h:159:47: 附注：in definition of macro ‘G_PASTE_ARGS’
 #define G_PASTE_ARGS(identifier1,identifier2) identifier1 ## identifier2
                                               ^
/usr/include/glib-2.0/glib/gmacros.h:162:44: 附注：in expansion of macro ‘G_PASTE’
 #define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1]
                                            ^
/usr/include/glib-2.0/glib/gatomic.h:136:5: 附注：in expansion of macro ‘G_STATIC_ASSERT’
     G_STATIC_ASSERT (sizeof *(atomic) == sizeof (gpointer));                 \
     ^
/usr/include/glib-2.0/glib/gthread.h:236:7: 附注：in expansion of macro ‘g_atomic_pointer_get’
     (!g_atomic_pointer_get (location) &&                             \
       ^
/usr/include/glib-2.0/gobject/gtype.h:1463:7: 附注：in expansion of macro ‘g_once_init_enter’
   if (g_once_init_enter (&g_define_type_id__volatile))  \
       ^
/usr/include/glib-2.0/gobject/gtype.h:1387:60: 附注：in expansion of macro ‘_G_DEFINE_TYPE_EXTENDED_BEGIN’
 #define G_DEFINE_TYPE_EXTENDED(TN, t_n, T_P, _f_, _C_)     _G_DEFINE_TYPE_EXTENDED_BEGIN (TN, t_n, T_P, _f_) {_C_;} _G_DEFINE_TYPE_EXTENDED_END()
                                                            ^
/usr/include/glib-2.0/gobject/gtype.h:1279:43: 附注：in expansion of macro ‘G_DEFINE_TYPE_EXTENDED’
 #define G_DEFINE_TYPE(TN, t_n, T_P)       G_DEFINE_TYPE_EXTENDED (TN, t_n, T_P, 0, {})
                                           ^
nm-l2tp-service.c:352:1: 附注：in expansion of macro ‘G_DEFINE_TYPE’
 G_DEFINE_TYPE (NML2tpPlugin, nm_l2tp_plugin, NM_TYPE_VPN_PLUGIN);
 ^
/usr/include/glib-2.0/glib/gmacros.h:162:53: 错误：typedef ‘_GStaticAssertCompileTimeAssertion_5’ locally defined but not used [-Werror=unused-local-typedefs]
 #define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1]
                                                     ^
/usr/include/glib-2.0/glib/gmacros.h:159:47: 附注：in definition of macro ‘G_PASTE_ARGS’
 #define G_PASTE_ARGS(identifier1,identifier2) identifier1 ## identifier2
                                               ^
/usr/include/glib-2.0/glib/gmacros.h:162:44: 附注：in expansion of macro ‘G_PASTE’
 #define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1]
                                            ^
/usr/include/glib-2.0/glib/gthread.h:241:5: 附注：in expansion of macro ‘G_STATIC_ASSERT’
     G_STATIC_ASSERT (sizeof *(location) == sizeof (gpointer));       \
     ^
/usr/include/glib-2.0/gobject/gtype.h:1477:7: 附注：in expansion of macro ‘g_once_init_leave’
       g_once_init_leave (&g_define_type_id__volatile, g_define_type_id); \
       ^
/usr/include/glib-2.0/gobject/gtype.h:1387:117: 附注：in expansion of macro ‘_G_DEFINE_TYPE_EXTENDED_END’
 #define G_DEFINE_TYPE_EXTENDED(TN, t_n, T_P, _f_, _C_)     _G_DEFINE_TYPE_EXTENDED_BEGIN (TN, t_n, T_P, _f_) {_C_;} _G_DEFINE_TYPE_EXTENDED_END()
                                                                                                                     ^
/usr/include/glib-2.0/gobject/gtype.h:1279:43: 附注：in expansion of macro ‘G_DEFINE_TYPE_EXTENDED’
 #define G_DEFINE_TYPE(TN, t_n, T_P)       G_DEFINE_TYPE_EXTENDED (TN, t_n, T_P, 0, {})
                                           ^
nm-l2tp-service.c:352:1: 附注：in expansion of macro ‘G_DEFINE_TYPE’
 G_DEFINE_TYPE (NML2tpPlugin, nm_l2tp_plugin, NM_TYPE_VPN_PLUGIN);
 ^
cc1: all warnings being treated as errors
make[3]: *** [nm-l2tp-service.o] 错误 1
make[3]: *** 正在等待未完成的任务....
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I.. -I/usr/include/NetworkManager -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/libnm-glib -Wall -std=gnu89 -g -O2 -Wshadow -Wmissing-declarations -Wmissing-prototypes -Wdeclaration-after-statement -Wstrict-prototypes -Wfloat-equal -Wno-unused-parameter -Wno-sign-compare -fno-strict-aliasing -Wno-unused-but-set-variable -Werror -MT nm_l2tp_pppd_plugin_la-nm-l2tp-pppd-plugin.lo -MD -MP -MF .deps/nm_l2tp_pppd_plugin_la-nm-l2tp-pppd-plugin.Tpo -c nm-l2tp-pppd-plugin.c -o nm_l2tp_pppd_plugin_la-nm-l2tp-pppd-plugin.o >/dev/null 2>&1
mv -f .deps/nm_l2tp_pppd_plugin_la-nm-l2tp-pppd-plugin.Tpo .deps/nm_l2tp_pppd_plugin_la-nm-l2tp-pppd-plugin.Plo
make[3]: 离开目录“/home/hougelangley/Source/NetworkManager-l2tp/src”
make[2]: *** [all] 错误 2
make[2]: 离开目录“/home/hougelangley/Source/NetworkManager-l2tp/src”
make[1]: *** [all-recursive] 错误 1
make[1]: 离开目录“/home/hougelangley/Source/NetworkManager-l2tp”
make: *** [all] 错误 2

**Comment by seriyps** [comment]
Project development was moved to https://github.com/nm-l2tp/network-manager-l2tp
If you feel that this problem wasn't resolved, please, re-create this issue on this new project.
